### ISSUE TITLE
Integración con Atlas

### ISSUE THREAD

**Issue by JunquerGJ** [2-DAST-2-CONTINUOUS/sisifo#1]
Hola.

Habíamos pensado en realizar una integración entre Atlas y Sísifo para que los resultados obtenidos por Sisifo fuesen cargados en Atlas.

De hecho, hasta podríamos almacenarlos a través de Atlas, si  fuese una solución valida.

¿ Podríais pasarnos una muestra del JSON con los resultados de Sisifo?

Un saludo

**Comment by irequena-dev** [comment]
Hola,

En cuanto tengamos el formato de salida os lo hacemos llegar.

Un saludo

**Comment by irequena-dev** [comment]
Hola, 

Como te hemos comentado en la issue del repositorio del hackathon, la estructura es la siguiente:

`[{ "name": String, "endpoints": [ { "url": String, "method": String } ], "severity": String, "description": String, "cwe": Integer }]`

Para un futuro, podríais habilitar un endpoint en el cual nosotros enviaríamos por POST el reporte y se cargaría en vuestra herramienta.

Un saludo
